config/routes.rb
Rails.application.routes.draw do
  resources :posts
  resources :codes
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'dashboards#index'
end

app/models/account.rb
class Account < ApplicationRecord
    validates :account_code, presence: true
    validates :name, presence: true

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
    validates :name, presence: true
end

app/models/code.rb
class Code < ApplicationRecord
    # create_table "codes", force: :cascade do |t|
    #     t.integer "code", null: false
    #     t.string "title", null: false
    #     t.text "body"
    #     t.integer "occurrence_count"
    #     t.datetime "created_at", null: false
    #     t.datetime "updated_at", null: false
    #   end

    validates :code, presence: true, numericality: {only_integer: true, greater_than_or_equal_to: 0}
    validates :title, presence: true
    validates :occurrence_count, presence: true
    validates :body, length: {maximum: 65_535}

    # def occurrence_count_add
    #     binding.pry
    #     if button_params == "追加"
    #         return @code.occurrence_count + params.require(:occurrence_count)
    #     else
    #         return params.require(:occurrence_count)
    #     end
    # end
end

app/models/company.rb
class Company < ApplicationRecord
    validates :name, presence: true
end

app/models/post.rb
class Post < ApplicationRecord
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    add_flash_types :success, :info, :warning, :danger
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
end

app/controllers/codes_controller.rb
class CodesController < ApplicationController

    before_action :set_code, only: %i[edit update destroy]
    # before_action :update_occurrence_count, only: %i[update]

    def index
        @codes = Code.all.order(code: "desc")
    end

    def new
        @code = Code.new
    end

    def create
        # binding.pry
        @code = Code.new(code_params)
        if @code.save
            redirect_to codes_path, success: 'エラー内容を保存しました。'
        else
            flash.now[:danger] = '作成に失敗しました。'
            render :new
        end
    end

    def show; end

    def edit; end

    def update
        unless button_params == '回数追加'
            if @code.update(code_params)
                redirect_to codes_path
            else
                render :edit
            end
        else
            @code.occurrence_count += 1
            if @code.save
                redirect_to codes_path
            else
                render :index
            end
        end

    end

    def destroy
        @code.destroy!
        redirect_to codes_path, success: '削除しました'
    end

    private

    def code_params
        params.require(:code).permit(:code, :title, :body, :occurrence_count)
    end

    def set_code
        @code = Code.find(params[:id])
    end

    def button_params
        params.require(:commit)
    end

    # def update_occurrence_count
    #     if button_params == '回数追加'
    #         # occurrence_count = params.require(:occurrence_count).to_i
    #         # @code.occurrence_count = @code.occurrence_count + occurrence_count
    #         @code.occurrence_count += 1
    #     end
    # end

end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
    def index; end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]

  # GET /posts or /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1 or /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to post_url(@post), notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :body)
    end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/codes_helper.rb
module CodesHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/codes/_code.html.slim
tr
  td
    = code.code
  td
    = code.title
  td
    = code.body
  td
    = code.occurrence_count
  td
    = l code.updated_at, format: :long
  td
    = form_with url: code_path(code), local: true, method: :PATCH do |f|
      / = f.text_field :occurrence_count, placeholder: '発生回数'
      = f.submit '回数追加', class: 'btn btn-primary btn-sm mr-1 ml-1'
      = link_to '編集', edit_code_path(code), class: "btn btn-success btn-sm mr-1 ml-1"
      = link_to '削除', code_path(code), method: :DELETE, data: {confirm: '削除しますか？' }, class: "btn btn-danger btn-sm mr-1 ml-1"

app/views/codes/_form.html.slim
= form_with model: @code, local: true do |f|
  = render 'shared/error_messages', model: f.object
  .form-group
    = f.label :code
    = f.text_field :code, class: "form-control"
  .form-group
    = f.label :title
    = f.text_field :title, class: "form-control"
  .form-group
    = f.label :body
    = f.text_area :body, rows: "5", class: "form-control"
  .form-group
    = f.label :occurrence_count
    = f.text_field :occurrence_count, class: "form-control"
  .actions
    = f.submit class: "btn btn-primary"

app/views/codes/edit.html.slim
.container.col-6.mb-5.pt-2
  = render 'form'

app/views/codes/index.html.slim
.container.mb-5.pt-2
  .row
    .col-md-12
      table.table.table-striped
        thead
          tr
            th[scope="col"]
              = Code.human_attribute_name(:code)
            th[scope="col"]
              = Code.human_attribute_name(:title)
            th[scope="col"]
              = Code.human_attribute_name(:body)
            th[scope="col"]
              = Code.human_attribute_name(:occurrence_count)
            th[scope="col"]
              = Code.human_attribute_name(:updated_at)
            th[scope="col"]
        tbody
          = render @codes

app/views/codes/new.html.slim
.container.col-6.mb-5.pt-2
  = render 'form'

app/views/dashboards/index.html.slim
p
  | ダッシュボード

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | SampleApp
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    script[src="https://code.jquery.com/jquery-2.2.4.min.js"]
    link[href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet"]
  body.hold-transition.sidebar-mini.layout-fixed
    .wrapper
      
      = render 'shared/header'
      = render 'shared/sidebar'
      = render 'shared/flash_message'
      .content-wrapper
        = yield
      = render 'shared/footer'

app/views/posts/_form.html.slim
= form_with(model: post, local: true) do |form|
  - if post.errors.any?
    #error_explanation
      h2
        = pluralize(post.errors.count, "error")
        |  prohibited this post from being saved:
      ul
        - post.errors.full_messages.each do |message|
          li
            = message
  .field
    = form.label :title
    = form.text_field :title
  .field
    = form.label :body
    = form.text_area :body
  .actions
    = form.submit

app/views/posts/edit.html.slim
h1
  | Editing Post
= render 'form', post: @post
= link_to 'Show', @post
|  | 
= link_to 'Back', posts_path

app/views/posts/index.html.slim
.container.mb-5.pt-2
  p#notice
    = notice
  h1
    | Posts
  table
    thead
      tr
        th
          | Title
        th
          | Body
        th[colspan="3"]
    tbody
      - @posts.each do |post|
        tr
          td
            = post.title
          td
            = post.body
          td
            = link_to 'Show', post
          td
            = link_to 'Edit', edit_post_path(post)
          td
            = link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' }
  br
  = link_to 'New Post', new_post_path

app/views/posts/new.html.slim
h1
  | New Post
= render 'form', post: @post
= link_to 'Back', posts_path

app/views/posts/show.html.slim
p#notice
  = notice
p
  strong
    | Title:
  = @post.title
p
  strong
    | Body:
  = @post.body
= link_to 'Edit', edit_post_path(@post)
|  | 
= link_to 'Back', posts_path

app/views/shared/_error_messages.html.slim
- if model.errors.any?
    #error_messages.alert.alert-danger
        ul.mb-0
            - model.errors.full_messages.each do |message|
                li
                    = message

app/views/shared/_flash_message.html.slim
- flash.each do |message_type, message|
    .alert class="alert-#{message_type} text-center"
      = message

app/views/shared/_footer.html.slim
footer.main-footer
  strong
    | Copyright © 2014-2021 
    a[href="https://adminlte.io"]
      | AdminLTE.io
    | .
  |  All rights reserved. 
  .float-right.d-none.d-sm-inline-block
    b
      | Version
    |  3.2.0 

app/views/shared/_header.html.slim
nav.main-header.navbar.navbar-expand.navbar-white.navbar-light
  ul.navbar-nav
    li.nav-item
      a.nav-link[data-widget="pushmenu" href="#" role="button"]
        i.fas.fa-bars
    li.nav-item.d-none.d-sm-inline-block
      - # <a href="index3.html" class="nav-link">Home</a>
      = link_to 'Home', root_path, class: "nav-link"
    li.nav-item.d-none.d-sm-inline-block
      a.nav-link[href="#"]
        | Contact
  ul.navbar-nav.ml-auto

app/views/shared/_sidebar.html.slim
aside.main-sidebar.sidebar-dark-primary.elevation-4
  a.brand-link[href="#"]
    / # <img src="dist/img/AdminLTELogo.png" alt="AdminLTE Logo" class="brand-image img-circle elevation-3" style="opacity: .8">
    span.brand-text.font-weight-light
      | work_sys
  .sidebar
    .user-panel.mt-3.pb-3.mb-3.d-flex
      .info
        a.d-block[href="#"]
          | UserName
    / # <div class="form-inline">
    nav.mt-2
      ul.nav.nav-pills.nav-sidebar.flex-column[data-widget="treeview" role="menu" data-accordion="false"]
        li.nav-item.menu-open
          a.nav-link.active[href="#"]
            i.nav-icon.fas.fa-tachometer-alt
            p
              |  エラー状況
              i.right.fas.fa-angle-left
          ul.nav.nav-treeview
            li.nav-item
              = link_to codes_path, class:"nav-link" do
                i.far.fa-circle.nav-icon
                p
                  | エラー一覧
            li.nav-item
              = link_to new_code_path, class:"nav-link" do
                i.far.fa-circle.nav-icon
                p
                  | エラー報告
            li.nav-item
              a.nav-link[href='#']
                i.far.fa-circle.nav-icon
                p
                  | エラー集計
        li.nav-item
          a.nav-link[href='#']
            i.nav-icon.fas.fa-tachometer-alt
            p
              | 工数
        li.nav-item
          a.nav-link[href="#"]
            i.nav-icon.fas.fa-chart-pie
            p
              |  品質
        li.nav-item
          a.nav-link[href="#"]
            i.nav-icon.fas.fa-table
            p
              |  固定費